# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://davidodun.github.io'
baseurl: '/TrueGroups'
title: 'TrueGroups'
description: 'A revolutionary unbiased group matchmaking platform.'
permalink: pretty
logo: "/assets/images/full_logo.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Docs
  url: /docs/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Blog Posts
    output: true
    description: "Updates and Milestones"
    feature_text:
    feature_image: "https://picsum.photos/2560/600?image=866"
